### ISSUE TITLE
Incompatible with Nengo 2.4.0

### ISSUE THREAD

**Issue by arvoelke** [psipeter/bioneuron_oracle#2]
Unsure of the cause. Here is a record of the error for convenience.

Output from Python:
```
<ipython-input-4-8e77e4465900> in step()
     23                     for nrn in self.neurons: #for each bioneuron
     24                         for syn in nrn.synapses[self.ens_pre_label][n]: #for each synapse conn. to input
---> 25                             syn.spike_in.event(t_neuron) #add a spike at time (ms)
     26         return step

RuntimeError: hoc error
```

Output from kernel stderr:
```
Additional mechanisms from files
 IKM.mod SlowCa.mod cad.mod h.mod kca.mod kfast.mod kslow.mod nap.mod nat.mod vecevent.mod
	1 
bad stack access: expecting (double); really (Object *)
NEURON: interpreter stack type error
 near line 0
 while (t < tstop) { fadvance() }
                                 ^
        NetCon[4].event(...)
oc_restore_code tobj_count=1 should be 0
```

This occurs even when `optimize=False`.

**Comment by arvoelke** [comment]
I used [git bisect](https://git-scm.com/docs/git-bisect) to locate the breaking commit in nengo: https://github.com/nengo/nengo/commit/ea5575eb9c80e24beb6fbe310231508688bcf034

It looks like the issue has to do with the signal `time` changing in `TransmitSpikes.make_step`, which means that NEURON no longer receives a scalar (but a singleton array instead).

**Comment by arvoelke** [comment]
The fix is to do the same thing done [here](https://github.com/nengo/nengo/blob/0693da37ab32c6e92c8ecfdf6e6533af60f54d31/nengo/builder/processes.py#L100). Namely, change `tback=time-dt` to `tback=time.item()-dt`. I have tested this on both Nengo 2.3.0 and 2.4.0 and it appears to work!

**Comment by psipeter** [comment]
Works for me too, thanks!
