### ISSUE TITLE
tests need better plot saving features

### ISSUE THREAD

**Issue by psipeter** [psipeter/bioneuron_oracle#4]
I'm having trouble using the `figure, (ax1, ax2, ax3) = plt.subplots(3, 1)` and `figure.savefig('name.png')` notation when running `py.test --plots='/path/to/plots/'`. Just needs a line or two to add the `--plots` variable to the figure name, I suspect.

**Comment by arvoelke** [comment]
See [here](https://github.com/nengo/nengo/blob/84db35b5dd673ec715c4b11a0a9afae074f1895f/nengo/utils/tests/test_connection.py#L39) for an example of how to use the `plt` test fixture to produce subplots.

The `savefig` is executed automatically by the test fixture (using the test name to determine the file name).

**Comment by arvoelke** [comment]
Regarding the other issue we were discussing over IM, I think you just need to change `[tool:pytest]` to `[pytest]` (as shown in the original `setup.cfg` I linked you to -- why did you change it?). For some reason this makes a difference for me and everything works fine.

You'll also want to split up your current feedforward unit test into at least 3 separate unit tests that generate 3 separate plots. Currently you are combining those 3 tests into 1.

**Comment by psipeter** [comment]
Hmm, that doesn't do it for me. Any time I run `py.test` with `--plots=anything`, I get the error. 

I changed it because pytest is giving me the warning:

`WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.`

**Comment by arvoelke** [comment]
Can you push the newest version (and check if any missing files)? These things shouldn't be different between us. Did you use `sudo apt-get install python-pytest`?

**Comment by psipeter** [comment]
Agreed, and pushed. I used `pip install -U pytest`. Running `pytest --version` gives `This is pytest version 3.0.7, imported from /home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/pytest.pyc`

**Comment by psipeter** [comment]
I just added an `__init__.py` in the tests folder, and now I'm not getting the error anymore...

Now all of my subplots are plotted in the same window, though.

**Comment by psipeter** [comment]
Clarification: the spike, voltage, and decode plots are are plotted on the same figure. This was why I was trying to avoid spamming the `plt.subplot(1,1,1)` command and use `figure, ax = plt.subplots(1,1)` for each separate figure.

**Comment by arvoelke** [comment]
See my comment about separating out the tests for separate figures.

**Comment by psipeter** [comment]
Thanks. I changed back to `[tool:pytest]` to avoid the warning, but plotting is still working.
