### ISSUE TITLE
Slicing for connections in/out of bioensembles

### ISSUE THREAD

**Issue by psipeter** [psipeter/bioneuron_oracle#5]
OK, the initial problem seems to be that the function on the connection isn't being set properly: 

```
Traceback (most recent call last):
  File "test_ff_input_output.py", line 107, in <module>
    test_slicing(plt)
  File "test_ff_input_output.py", line 51, in test_slicing
    nengo.Connection(lif1,bio[0],synapse=tau_neuron)
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/base.py", line 35, in __call__
    inst.__init__(*args, **kwargs)
  File "/home/pduggins/bioneuron_oracle/bioneuron_oracle/BioConnection.py", line 40, in __init__
    super(BioConnection, self).__init__(pre, post, solver=solver, **kwargs)
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/connection.py", line 411, in __init__
    self.function_info = function  # Must be set after transform
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/base.py", line 106, in __setattr__
    super(NengoObject, self).__setattr__(name, val)
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/config.py", line 453, in __setattr__
    reraise(exc_info[0], exc_info[1], None)
  File "<string>", line 2, in reraise
nengo.exceptions.ValidationError: BioConnection.function: function output size is incorrect; should return a vector of size 1
```

I poked around a bit in `nengo.connection.py` to see what was going on with initialization of transforms and functions. Looks like they are set to `nengo.params.Default` in` __init__()` of `nengo.connection.py`. I tried setting them to this in my monkeypatched `BioConnection()` class, but got the same error. Next I tried adding this to `BioConnection.__init___()`

```
function_info = ConnectionFunctionParam(
        'function', default=None, optional=True)
transform = TransformParam('transform', default=np.array(1.0))
```

but that broke normal connections. Can @arvoelke make some suggestions (or solve it, and tell me the process in hindsight :P)

**Comment by arvoelke** [comment]
So the way you're trying to do it right now won't work in principle. You're trying to connect `lif1`, which is 2-dimensional, to `bio[0]`, which is 1-dimensional. In order to do that you need a function with an output size of 1. Or, more simply, change `lif1` to 1-dimensional (but keep `bio` 2-dimensional). If I recall the problem correctly, this will basically compile but not simulate properly (it should be folding a transform like `[[1, 0]]` [or its transpose] into the decoders).

**Comment by arvoelke** [comment]
By the way, you currently have simulations running in the global namespace. This makes it a little annoying to selectively run tests using the `py.test -k` option because it will always run those extra simulations that I don't want to run.

**Comment by arvoelke** [comment]
> (it should be folding a transform like [[1, 0]] [or its transpose] into the decoders).

Actually it might be [more complicated than that](https://github.com/nengo/nengo/blob/master/nengo/builder/connection.py#L235) (see `pre_slice` and `post_slice`). If it's not obvious how to proceed I'd just keep this as a known limitation for now.

**Comment by psipeter** [comment]
Hmm, it's not obvious how to proceed, but I think connecting to/from dimensions of bioensembles is a pretty essential feature that I'll want to utilize going forward. I'd like to take the time to get it working soon, unless you think it'll take more than a few days.

**Comment by psipeter** [comment]
Fixed by using `transform=full_transform()`, calling `neuron.init()` in a few extra places, and checking `isinstance(conn.post.obj.neuron_type, BahlNeuron)` for slices
