### ISSUE TITLE
Connections out of bioensembles

### ISSUE THREAD

**Issue by psipeter** [psipeter/bioneuron_oracle#6]
I added some more code to our `build_connections()` that is supposed to handle connections out of bioensembles (either to other bioensembles or other nengo nodes/neuron_types). It's under the `if conn_out_bioneuron:` block. If you comment out the lines

```
       # Extra stuff from nengo's build_connection()
        model.sig[conn]['in'] = model.sig[conn_pre]['out']
        in_signal = model.sig[conn]['in']
        # Add operator for applying weights
        model.sig[conn]['weights'] = Signal(
            weights, name="%s.weights" % conn, readonly=True)
        signal = Signal(np.zeros(conn.size_out), name="%s.weighted" % conn)
        model.add_op(Reset(signal))
        op = ElementwiseInc if weights.ndim < 2 else DotInc
        model.add_op(op(model.sig[conn]['weights'],
                        in_signal,
                        signal,
                        tag="%s.weights_elementwiseinc" % conn))
        # Add operator for filtering
        if conn.synapse is not None:
            signal = model.build(conn.synapse, signal)
        # Store the weighted-filtered output in case we want to probe it
        model.sig[conn]['weighted'] = signal
        # Copy to the proper slice
        model.add_op(Copy(signal, model.sig[conn]['out'], dst_slice=conn.post_slice))
```

then the code doesn't throw any errors, but no signals are transmitted out (running `test_ff_input_output.py` will create a plot that shows the LIF neurons have not been stimulated). I grabbed that code from the nengo `build_connections()`, figuring I was failing to create or add the proper signals/operators, but there's currently some shape mismatching going on, and I'm not sure how much of this is necessary anyway.

**Comment by arvoelke** [comment]
There's got to be an easier way to do this. We already have bio -> bio working right? I't just bio -> other that is the problem? This is related to the task of probing the bio ensemble. I think we can leverage existing code in Nengo to do this for us at a later time. For instance this may be 'easily' achievable by creating a custom decoder solver that simply returns some fixed bio_decoders (and ignores the given activities and targets). This would be done in the monkeypatch (rather than the build_connection).

**Comment by psipeter** [comment]
I created a custom decoder class that stores `decoders_bio`, which has made decoding and connections out of bioensembles possible (see `test_decode` tests). I'm currently creating these solvers within the network and setting `conn.solver=BioSolver()` for any connection out of a bioensemble (can monkeypatch later).

Unfortunately, I'm still running into the same problem when I try to slice or transform these output connections. Without any special handling, our `build_connections()` for `isinstance(conn.post, BahlNeuron)` (or slice/object equivalent) just does `return nengo.builder.connection.build_connection(model, conn)`. This grabs the correct decoders, but doesn't seem to apply the transform or slice properly.

My attempts at creating an `if conn_out_bioneuron: [...]` condition have failed so far, with the same size errors in multiplication that I originally mentioned (that, or it just transmits zero). Could use a little help here. As you said, bio-bio connections do work, but I can't get the integrator to work (in a non-hacky way) until I get the bio-[transform]-X working.

**Comment by arvoelke** [comment]
> Unfortunately, I'm still running into the same problem when I try to slice or transform these output connections. Without any special handling, our build_connections() for isinstance(conn.post, BahlNeuron) (or slice/object equivalent) just does return nengo.builder.connection.build_connection(model, conn). This grabs the correct decoders, but doesn't seem to apply the transform or slice properly.

This is surprising to me. Can you point me to the code you're using to check this?

**Comment by psipeter** [comment]
Here's the [relevant builder function](https://github.com/psipeter/bioneuron_oracle/blob/dd690be4a0e7767942ca35b7958a9b37562842e2/bioneuron_oracle/builder.py#L116-L252), with the `if conn_out_bioneurons:` commented out at the end.

Then run the tests in [test_input_output.py](https://github.com/psipeter/bioneuron_oracle/blob/dd690be4a0e7767942ca35b7958a9b37562842e2/bioneuron_oracle/tests/test_input_output.py). You should see` test_transform_out` and `test_slice_out` fail.

**Comment by arvoelke** [comment]
By the way is there a good reason you use `slice_pre=False` when calling `full_transform`? Wouldn't that ignore the any slices _from_ an ensemble to bio?

**Comment by psipeter** [comment]
Nope, no good reason...seems to work without it though?

**Comment by arvoelke** [comment]
Yeah I think that will work since you don't have any tests that connect say `lif[0]` to `bio` (or say `bio[0]` to `bio[0]`). I suspect those will fail.

**Comment by arvoelke** [comment]
Sorry there's a lot going on in the unit tests so this might take a while. Normally unit tests should be more isolated and lower level (testing a single "unit" of code) rather than a whole bunch of things in combination -- but I understand why you did things this way.

**Comment by psipeter** [comment]
I just add another [test](https://github.com/psipeter/bioneuron_oracle/blob/5abc275a3038dc5efe737e24a2d73e185e576c18/bioneuron_oracle/tests/test_input_output.py#L213), which connects `lif[0]` to `bio[0]`, and it actually fails when `slice_pre=True`.

I guess I could use some examples of lower-level unit tests. My reasoning for doing them this way was that, if (say) a connection/slice/transform failed, the test for that added feature would fail at build time, so it wouldn't take time to run. But if the connection was made, but didn't successfully transmit anything, then I need to run the simulation for a while to show that the spiking/decoded behavior of the bioensemble wasn't changing like the signal. But maybe there's a better way...

**Comment by arvoelke** [comment]
At a meta level, let me just say that unit testing works in mysterious / unintuitive ways. You may not think it's being effective when you only look at small parts in isolation, but half the time this process uncovers issues you weren't even testing, or when changing some code it will fail in seemingly unrelated ways. It's kind of like an emergent property of integrating complex systems. It's hard to appreciate until you see results for yourself though. afk for a bit.

**Comment by psipeter** [comment]
I found a hacky solution for slicing and transforms out of bioensembles, which basically recycles most of the nengo `build_connection` code but changes [this line](https://github.com/nengo/nengo/blob/bf47e495bbc43538584457748535d9f4ae50a1c0/nengo/builder/connection.py#L263) to `op = DotInc`. Not too elegant, and may fail for cases I haven't tested yet.

Basic input/output tests are passing, but my version of test_integrator doesn't produce a good decoding.
