### ISSUE TITLE
Slicing with trained_weights fails

### ISSUE THREAD

**Issue by psipeter** [psipeter/bioneuron_oracle#8]
I'm getting a ValueError related to the shape of the weights/decoders when I try connecting into `bio[0]` in `test_slice_post_spike_matching` in `test_input_output_spike_matching.py`.  

`
        # network = spike_match_train(network, method="1-N",
        #                             params=evo_params, plots=True)
    
>       with Simulator(model, dt=dt_nengo) as sim:

test_input_output_spike_matching.py:198: 

../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/simulator.py:153: in __init__
    self.model.build(network, progress_bar=self.progress_bar)
../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/builder.py:121: in build
    built = Builder.build(self, obj, *args, **kwargs)
../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/builder.py:216: in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/network.py:115: in build_network
    model.build(conn)
../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/builder.py:121: in build
    built = Builder.build(self, obj, *args, **kwargs)
../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/builder.py:216: in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
../builder.py:247: in build_connection
    model, conn, rng, transform)
../../../.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/connection.py:125: in build_decoders
    multiply(transform, decoders.T))

x = array([[ 1.],
       [ 0.]]), y = array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  ...0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

    def multiply(x, y):
        if x.ndim <= 2 and y.ndim < 2:
            return x * y
        elif x.ndim < 2 and y.ndim == 2:
            return x.reshape(-1, 1) * y
        elif x.ndim == 2 and y.ndim == 2:
            return np.dot(x, y)

ValueError: shapes (2,1) and (100,20) not aligned: 1 (dim 1) != 100 (dim 0)
`

The error is being thrown when `build_decoders(model, conn, rng, transform)` , specifically when `weights = (decoders.T if conn.solver.weights else multiply(transform, decoders.T))` is called. 

I've had some troubles with `build_decoders` elsewhere in the trained_weights approach, but I hacked a solution where I stored the weights in `solver_info` then set it manually in our custom `build_connection`. This doesn't seem to avoid this error though, and I can't find a workaround. @arvoelke I know we haven't worked together on the non-oracle portion of this yet, but I'm hoping there's a relatively straightforward way to make our `build_connection()` work better with weights, not decoders...maybe starting by somehow letting it know that we're working with weights.

**Comment by arvoelke** [comment]
Have you tried setting the `solver.weights` to True?

**Comment by psipeter** [comment]
Yes, but I always get `ReadonlyError: TrainedSolver.weights: weights is read-only and cannot be changed`. Where is the proper place to set this (I've tried in TrainedSolver.__init__() and various places in the builder)? I don't think this will fix the problem but it's a start.

**Comment by arvoelke** [comment]
You should pass it as an argument to `super`, due to how the `FrozenObject` class works. See examples here: https://github.com/nengo/nengo/blob/master/nengo/solvers.py

~~It's worth doing because a distinction needs to be made somewhere to handle the fact that these weights are now different shapes.~~

**Comment by arvoelke** [comment]
~~Actually these are still decoders, so it's probably not right to set `weights` to True. I'll look at the code.~~

**Comment by arvoelke** [comment]
Okay they are weights right? According to this line: https://github.com/psipeter/bioneuron_oracle/blob/wip/bioneuron_oracle/tests/test_input_output_spike_matching.py#L182
they are `n_neurons` by `n_neurons`. So try setting `weights` to True and see how things change.

**Comment by psipeter** [comment]
~~This does remove the bug, but somehow prevents the weights from being set for all the other tests (they are initialized to zero but not updated as intended, so the bioneurons don't spike at all). I'm looking into this now.~~

**Comment by psipeter** [comment]
I was wrong, it looks like setting weights=True in `super` fixed the problem and doesn't disrupt other functionality. Too easy.

**Comment by arvoelke** [comment]
> Too easy.

Bring on more of those impossible-to-trace soul-crushing bugs!

**Comment by psipeter** [comment]
> Bring on more ... bugs

Be careful what you wish for ... :sweat_smile:
